## Lab_AI_1&2

In [2]:
from matplotlib import pylab
import numpy as np 
import pandas as pd 
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

print(pylab.__version__)
print(sns.__version__)
print(np.__version__)
print(pd.__version__)
print(matplotlib.__version__)
print(matplotlib.__version__)

2.5.1
0.13.2
2.5.1
3.0.5
3.11.1
3.11.1

In [6]:
df=pd.read_csv(r"C:\Users\abdur\Downloads\archive (2)\patients_data.csv")
df.head()

C:\Users\abdur\AppData\Local\Temp\ipykernel_17920\5971103.py:1: DtypeWarning: Columns (0: Age Bracket, 1: Contracted from which Patient (Suspected), 2: Nationality, 3: Type of transmission, 4: Status Change Date, 5: Source_3, 6: Backup Notes) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r"C:\Users\abdur\Downloads\archive (2)\patients_data.csv")

,Patient Number,State Patient Number,Date Announced,Estimated Onset Date,Age Bracket,Gender,Detected City,Detected District,Detected State,State code,...,Contracted from which Patient (Suspected),Nationality,Type of transmission,Status Change Date,Source_1,Source_2,Source_3,Backup Notes,Num Cases,Entry_ID
0,1.0,KL-TS-P1,30/01/2020,NaN,20,F,Thrissur,Thrissur,Kerala,KL,...,NaN,India,Imported,14/02/2020,https://twitter.com/vijayanpinarayi/status/122...,https://weather.com/en-IN/india/news/news/2020...,NaN,Student from Wuhan,1.0,NaN
1,2.0,KL-AL-P1,02/02/2020,NaN,NaN,NaN,Alappuzha,Alappuzha,Kerala,KL,...,NaN,India,Imported,14/02/2020,https://www.indiatoday.in/india/story/kerala-r...,https://weather.com/en-IN/india/news/news/2020...,NaN,Student from Wuhan,1.0,NaN
2,3.0,KL-KS-P1,03/02/2020,NaN,NaN,NaN,Kasaragod,Kasaragod,Kerala,KL,...,NaN,India,Imported,14/02/2020,https://www.indiatoday.in/india/story/kerala-n...,https://twitter.com/ANI/status/122422148580539...,https://weather.com/en-IN/india/news/news/2020...,Student from Wuhan,1.0,NaN
3,4.0,DL-P1,02/03/2020,NaN,45,M,East Delhi (Mayur Vihar),East Delhi,Delhi,DL,...,NaN,India,Imported,15/03/2020,https://www.indiatoday.in/india/story/not-a-ja...,https://economictimes.indiatimes.com/news/poli...,NaN,Travel history to Italy and Austria,1.0,NaN
4,5.0,TS-P1,02/03/2020,NaN,24,M,Hyderabad,Hyderabad,Telangana,TG,...,NaN,India,Imported,02/03/2020,https://www.deccanherald.com/national/south/qu...,https://www.indiatoday.in/india/story/coronavi...,https://www.thehindu.com/news/national/coronav...,"Travel history to Dubai, Singapore contact",1.0,NaN

In [8]:
df.shape

(247236, 22)

In [11]:
df.describe()

       Patient Number  Estimated Onset Date      Num Cases       Entry_ID
count    99793.000000                   0.0  247223.000000  219051.000000
mean     50683.789174                   NaN      13.904556  109495.161328
std      29418.719380                   NaN     149.163415   63216.612683
min          1.000000                   NaN  -11162.000000       1.000000
25%      24949.000000                   NaN       1.000000   54717.500000
50%      50945.000000                   NaN       1.000000  109507.000000
75%      75896.000000                   NaN       2.000000  164223.500000
max     102610.000000                   NaN   10320.000000  218999.000000

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 247236 entries, 0 to 247235
Data columns (total 22 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Patient Number                             99793 non-null   float64
 1   State Patient Number                       110759 non-null  str
 2   Date Announced                             247234 non-null  str
 3   Estimated Onset Date                       0 non-null       float64
 4   Age Bracket                                108030 non-null  object
 5   Gender                                     110800 non-null  str
 6   Detected City                              12052 non-null   str
 7   Detected District                          238066 non-null  str
 8   Detected State                             247217 non-null  str
 9   State code                                 247114 non-null  str
 10  Current Status                             247224 non-null  str
 11  Notes                                      107663 non-null  str
 12  Contracted from which Patient (Suspected)  1924 non-null    str
 13  Nationality                                1554 non-null    str
 14  Type of transmission                       2990 non-null    str
 15  Status Change Date                         27780 non-null   str
 16  Source_1                                   243632 non-null  str
 17  Source_2                                   6265 non-null    str
 18  Source_3                                   598 non-null     str
 19  Backup Notes                               361 non-null     str
 20  Num Cases                                  247223 non-null  float64
 21  Entry_ID                                   219051 non-null  float64
dtypes: float64(4), object(1), str(17)
memory usage: 41.5+ MB