## Matplotlib

In [4]:
from matplotlib import pylab
import numpy as np 
import pandas as pd 
import matplotlib 

print(pylab.__version__)
print(np.__version__)
print(pd.__version__)
print(matplotlib.__version__)

2.5.1
2.5.1
3.0.5
3.11.1

In [18]:
df=pd.read_csv(r"C:\Users\abdur\Downloads\archive (1)\psl2026_matches.csv")
df.head(3)

,match_id,date,stage,venue,city,team1,team2,toss_winner,toss_decision,team1_score,team1_wickets,team1_overs,team2_score,team2_wickets,team2_overs,result,winner,win_margin,player_of_match
0,1,2026-03-26,League,Gaddafi Stadium,Lahore,Lahore Qalandars,Hyderabad Kingsmen,Lahore Qalandars,bat,162.0,8.0,20.0,163.0,4.0,17.3,Hyderabad Kingsmen won by 6 wkts,Hyderabad Kingsmen,6 wickets,Maaz Sadaqat
1,2,2026-03-27,League,National Bank Cricket Arena,Karachi,Karachi Kings,Quetta Gladiators,Karachi Kings,bat,178.0,6.0,20.0,162.0,9.0,20.0,Karachi Kings won by 16 runs,Karachi Kings,16 runs,David Warner
2,3,2026-03-28,League,Gaddafi Stadium,Lahore,Pindiz,Peshawar Zalmi,Peshawar Zalmi,field,148.0,9.0,20.0,149.0,3.0,16.4,Peshawar Zalmi won by 7 wkts,Peshawar Zalmi,7 wickets,Babar Azam

In [14]:
df.shape

(44, 19)

In [16]:
df.describe()

,match_id,team1_score,team1_wickets,team1_overs,team2_score,team2_wickets,team2_overs
count,44.000000,43.000000,43.000000,43.000000,43.000000,43.00000,43.000000
mean,22.500000,170.953488,6.744186,19.732558,156.976744,6.44186,18.306977
std,12.845233,25.450188,1.989173,0.763364,22.020000,2.71067,2.080224
min,1.000000,118.000000,3.000000,16.500000,80.000000,2.00000,12.300000
25%,11.750000,155.500000,5.000000,20.000000,144.500000,4.00000,17.250000
50%,22.500000,174.000000,6.000000,20.000000,161.000000,7.00000,19.300000
75%,33.250000,186.000000,8.000000,20.000000,172.500000,9.00000,20.000000
max,44.000000,246.000000,10.000000,20.000000,192.000000,10.00000,20.000000

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   match_id         44 non-null     int64
 1   date             44 non-null     str
 2   stage            44 non-null     str
 3   venue            44 non-null     str
 4   city             44 non-null     str
 5   team1            44 non-null     str
 6   team2            44 non-null     str
 7   toss_winner      44 non-null     str
 8   toss_decision    43 non-null     str
 9   team1_score      43 non-null     float64
 10  team1_wickets    43 non-null     float64
 11  team1_overs      43 non-null     float64
 12  team2_score      43 non-null     float64
 13  team2_wickets    43 non-null     float64
 14  team2_overs      43 non-null     float64
 15  result           44 non-null     str
 16  winner           44 non-null     str
 17  win_margin       43 non-null     str
 18  player_of_match  43 non-null     str
dtypes: float64(6), int64(1), str(12)
memory usage: 6.7 KB